bs_train: 120
bs_valid: 120
bs_test: 120
max_epoch: 200
dataset: {
  name: ModelNet40,
  train: {
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml,
    others: {
      subset: train,
      n_point: 1024,
    }
  },
  valid: {
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml,
    others: {
      subset: test,
      n_point: 1024,
    }
  },
  test: {
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml,
    others: {
      subset: test,
      n_point: 1024,
    }
  },
}
model: {
  name: PointNetCls,
  n_class: 40,
  n_point: 1024,
  use_normals: False,
}
loss: {
  name: PointNetLoss,
}
optimizer: {
  type: AdamW,
  kwargs: {
    lr: 1.0e-3,
    weight_decay: 1.0e-4,
  }
}
scheduler: {
  type: function,
}
transforms: {
  
}

