bs_train: 480
bs_valid: 480
bs_test: 480
max_epoch: 2

dataset:
  name: ModelNet40
  train:
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml
    others:
      subset: train
      n_point: 1024
  valid:
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml
    others:
      subset: test
      n_point: 1024
  test:
    _base_: configs/datasets/datasets_ModelNet/ModelNet40.yaml
    others:
      subset: test
      n_point: 1024

model:
  name: PointNetCls
  n_class: 40
  n_point: 1024
  use_normals: False

loss:
  name: PointNetLoss

optimizer:
  name: adamw
  lr: 1.0e-3
  kwargs:
    weight_decay: 1.0e-4

scheduler: 
  name: cosine
  n_epoch: 200

