optimizer: {
  type: AdamW,
  kwargs: {
    lr: 1.0e-3,
    weight_decay: 1.0e-4,
  },
}
scheduler: {
  type: CosineAnnealingLR,
  kwargs: {
    epochs: 200,
    eta_min: 1.0e-3,
  },
}
dataset: {
  name: ShapeNet,
  train: {
    _base_: configs/datasets/datasets_ShapeNet/ShapeNet.yaml,
    others: {
      subset: train,
    },
  },
  valid: {
    _base_: configs/datasets/datasets_ShapeNet/ShapeNet.yaml,
    others: {
      subset: test,
    },
  },
  test: {
    _base_: configs/datasets/datasets_ShapeNet/ShapeNet.yaml,
    others: {
      subset: test,
    },
  },
}
model: {
  name: PointNetPartSeg,
  use_normals: False,
}
loss: {
  loss_name: PointNetLoss,
  mat_diff_loss_scale: 0.001,
}
bs_train: 16
bs_test: 16
n_point: 2048
max_epoch: 200
