name: ShapeNetPart
pointcloud_path: data/ShapeNetPart
n_point: 1024
cat2id: {
  'airplane': 0,
  'bag': 1,
  'cap': 2,
  'car': 3,
  'chair': 4, 
  'earphone': 5,
  'guitar': 6,
  'knife': 7,
  'lamp': 8,
  'laptop': 9,
  'motor': 10,
  'mug': 11,
  'pistol': 12,
  'rocket': 13,
  'skateboard': 14,
  'table': 15
}
seg_num: [4, 2, 2, 4, 4, 3, 3, 2, 4, 2, 6, 2, 3, 3, 3, 3]
index_start: [0, 4, 6, 8, 12, 16, 19, 22, 24, 28, 30, 36, 38, 41, 44, 47]