optimizer: {
  type: AdamW,
  kwargs: {
    lr: 1.0e-3,
    weight_decay: 1.0e-4,
  },
}
scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 10,
  },
}
dataset: {
  name: S3DIS,
  train: {
    _base_: cfgs/configs_datasets/S3DIS.yaml,
    others: {
      subset: train,
    },
  },
  valid: {
    _base_: cfgs/configs_datasets/S3DIS.yaml,
    others: {
      subset: test,
    },
  },
  test: {
    _base_: cfgs/configs_datasets/S3DIS.yaml,
    others: {
      subset: test,
    },
  },
}
model: {
  name: DGCNNSemSeg,
  k_point: 20,
  d_embed: 1024,
  dropout: 0.5,
}
bs_train: 32
bs_test: 16
n_point: 4096
max_epoch: 100
